version: 2.1

orbs:
  maven: circleci/maven@1.0.1

workflows:
  maven_test:
    docker:
      - image: circleci/openjdk:10-jdk-node
    jobs:
      - maven/test # checkout, build, test, and upload test results
