version: 2.1

orbs:
  maven: circleci/maven@1.0.1

executors:
  maven:
    description: The docker container to use when running Maven builds
    docker:
      - image: circleci/openjdk:10-jdk-node

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
